### ISSUE TITLE
Getting local IP addresses fails on some OSX machines

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#640] opened 2021-06-15 13:17 UTC
**Context**
We see intermittent issues when listing all local interfaces which are then used for the direct network connection.
These are then sent to the app so it can connect back.

```
[06:01:11] dbug: 06:01:11.9377920 *** Executing 'System.Buffers.Tests' on tvos-device 'DNCENGTVOS-005' ***
[06:01:16] dbug: 06:01:16.9646910 Test execution started
[06:01:18] fail: Application run failed:
    System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): nodename nor servname provided, or not known
        at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in System.Net.NameResolution.dll:token 0x6000041+0x5a
        at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family) in System.Net.NameResolution.dll:token 0x6000028+0x72
        at System.Net.Dns.GetHostEntry(String hostNameOrAddress) in System.Net.NameResolution.dll:token 0x6000027+0x0
        at Microsoft.DotNet.XHarness.iOS.Shared.Utilities.Helpers.GetLocalIpAddresses() in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Helpers.cs:line 59
        at Microsoft.DotNet.XHarness.Apple.AppTester.GetDeviceArguments(AppBundleInformation appInformation, IDevice device, Boolean isWatchTarget, XmlResultJargon xmlResultJargon, String[] skippedMethods, String[] skippedTestClasses, ListenerTransport deviceListenerTransport, Int32 deviceListenerPort, String deviceListenerTmpFile, IEnumerable`1 extraAppArguments, IEnumerable`1 extraEnvVariables) in /_/src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs:line 564
        at Microsoft.DotNet.XHarness.Apple.AppTester.TestApp(AppBundleInformation appInformation, TestTargetOs target, IDevice device, IDevice companionDevice, TimeSpan timeout, TimeSpan testLaunchTimeout, IEnumerable`1 extraAppArguments, IEnumerable`1 extraEnvVariables, XmlResultJargon xmlResultJargon, String[] skippedMethods, String[] skippedTestClasses, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs:line 190
        at Microsoft.DotNet.XHarness.Apple.TestOrchestrator.ExecuteApp(AppBundleInformation appBundleInfo, TestTargetOs target, IDevice device, IDevice companionDevice, TimeSpan timeout, TimeSpan launchTimeout, CommunicationChannel communicationChannel, XmlResultJargon xmlResultJargon, IEnumerable`1 singleMethodFilters, IEnumerable`1 classMethodFilters, IReadOnlyCollection`1 environmentalVariables, IEnumerable`1 passthroughArguments, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs:line 155
        at Microsoft.DotNet.XHarness.Apple.BaseOrchestrator.OrchestrateRun(TestTargetOs target, String deviceName, Boolean resetSimulator, Boolean enableLldb, AppBundleInformation appBundleInfo, Func`2 executeMacCatalystApp, Func`4 executeApp, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs:line 178
```

Full logs: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-xharness-refs-pull-639-merge-174d8070e8dd4887b2/System.Buffers.Tests/console.81038bca.log?sv=2019-07-07&se=2021-07-05T13%3A00%3A05Z&sr=c&sp=rl&sig=goNJEtHi%2FkfJXWPlsH%2FyV680jUXxg9YOGtNhVgJAGSk%3D

**Goal**
- Add retries
- Possibly not do this when using TCP tunnel (not sure this is possible though as network is a fallback solution for tunnel)

**Comment by premun** [comment] 2021-06-18 12:47
These are the machines where this happened:
- `DNCENGMAC005`
- `DNCENGMAC016`

I found out that the OSX machine where it failed reproduces it 100% of the time:

Program.cs
```csharp
using System;
using System.Collections.Generic;
using System.Net;

Console.WriteLine(string.Join(Environment.NewLine, (IEnumerable<IPAddress>)Dns.GetHostEntry(Dns.GetHostName()).AddressList));
```

Program.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by premun** [comment] 2021-06-18 13:42
So adding this line into `/private/etc/hosts` and rebooting did the trick:
```
127.0.0.1   DNCENGMAC016.local
```

The command for that is:
```sh
echo "127.0.0.1        $(hostname -f)" | sudo tee -a /etc/hosts
```

**Comment by premun** [comment] 2021-06-18 14:04
@akoeplinger do you know if we hit this issue on OSX in BCL before? I feel like we must have and maybe there's a better way than to update our whole infra?

(not really know whom to ask)

**Comment by aik-jahoda** [comment] 2021-06-21 14:54
I can confirm the code above don't return loopback addresses. Can you use "localhost" instead of Dns.GetHostName()?
cc @ManickaP

**Comment by ManickaP** [comment] 2021-06-21 20:33
AFAIK you'll get only the basic 2 addresses for localhost:
```
::1
127.0.0.1
```

We have a check for your own hostname and you'll get addresses of all interfaces (including link-local IPv6), e.g.:
```
127.0.1.1
192.168.0.222
192.168.122.1
171.34.0.1
171.26.0.1
3b00:4d20:151:15f::8
fe80::83b2:c96d:f4d0:4394%2
fe80::fc54:ff:fe1d:ec8c%6
```

So this depends on what the code is trying to achieve.

**Comment by premun** [comment] 2021-06-22 07:55
@ManickaP I have stated my intention bad. The intention is to provide all local network addresses for a hostname (where hostname=localhost in the sense I execute the command on the machine that I want the addresses for).

The output I want and the output I get on some OSX machines is this:
```
fe80::1%1
127.0.0.1
::1
169.254.126.189
169.254.115.252
10.105.153.108
fe80::4b3:f6e7:32b7:a212%6
fe80::1858:1176:9ce8:84ca%4
fe80::1c4d:e153:16de:5b38%8
2001:4898:9008:60:1478:ba3:2557:99b1
2001:4898:9008:60:949c:46e9:eb06:5f8
2001:4898:9008:60:7515:9843:fc51:5742
2001:4898:9008:60:e4dc:5d13:8b86:a642
2001:4898:9008:60:851b:c4e2:f1d4:33e4
2001:4898:9008:60:3861:fb19:f837:ff0f
2001:4898:9008:60:f8ae:81b3:3c81:3c84
2001:4898:9008:60:58cf:98a:27d8:56b4
fe80::aede:48ff:fe00:1122%5
fe80::60c7:97ff:fe82:8acc%10
fe80::60c7:97ff:fe82:8acc%11
fe80::d1f7:9337:bf86:4ffc%17
fe80::85fe:6d27:a939:ee55%18
```

However, on some machines, I get an exception when calling:
```
Dns.GetHostEntry(Dns.GetHostName())
```

The only remedy is to add this to `/etc/hosts`:
```
127.0.0.1    <hostname>
```

The machines were all re-imaged by DDFUN and some seem to work and some don't and I don't know if there's a difference between them.

Just felt a bit off that this call would blow up, so I asked around.

**Comment by ManickaP** [comment] 2021-06-23 13:01
This is an error returned by the OS: `EAI_NONAME` or `EAI_NODATA` from [`getaddrinfo`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getaddrinfo.3.html)

I don't have an access to any iOS/OSX, so I cannot reproduce this. Seeing `DNCENGMAC016.local` there, do you have properly set up hostname (`/etc/hostname`)? The `.local` suffix suggests Avahi/bonjour mDNS naming scheme.

This functionality depends heavily on the OS settings. Having properly set up /etc/hosts is not a bad way to solve this problem IMHO.

**Comment by premun** [comment] 2021-06-23 14:16
Running `hostname` returns `DNCENGMAC016.local`. I didn't find `/etc/hostname`.

> Having properly set up /etc/hosts is not a bad way to solve this problem IMHO.

Alright, will do then! Thanks!

**Comment by premun** [comment] 2021-06-24 12:41
@ManickaP so there is no other way to find out the local network addresses other than this?

**Comment by ManickaP** [comment] 2021-06-24 13:27
You could also list all network interfaces and get addresses from them: https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface?view=net-5.0, i.e.: `NetworkInterface.GetAllNetworkInterfaces()`.

But this might be quite slower and you might hit even more problems with it. I know we had some recent work done it by @wfurt since it was unexpectedly throwing in some cases.

**Comment by wfurt** [comment] 2021-06-24 13:43
What DNS feels about the name and what is actually configure on interfaces can be (completely) disjoined sets. 
DNS typically does not include the IPv6 link-local fe80:: address e.g. has only the one global reachable. 

`/etc/hostname` does not exist on OSX @ManickaP. If anything the (/private)/etc/hosts would be right fix. e.g. it would complement DNS looking for given name. 

My recommendation would be to catch the socket errno and give 1-3 retries to see if that is just transient error or if that is mis-configured system. (or the dhcp-dns binding got busted)

**Comment by premun** [comment] 2021-06-24 13:45
That makes sense.

Thank you both!

**Comment by akoeplinger** [comment] 2021-06-29 14:01
In Mono we did occasionally run into an issue where resolving the machine name to IP addresses didn't work due to some weirdness with the DNS servers in the MSFT lab network. I think I'd prefer using `NetworkInterface.GetAllNetworkInterfaces()` instead.

**Closed** 2021-07-07 08:27 UTC
Labels: apple, bug
