### ISSUE TITLE
Can Xharness.CLI boot Android emulators?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/xharness#201] opened 2020-05-14 22:17 UTC
XHarness.CLI for iOS is able to boot iOS simulators without help, is it possible to do it for Android as well?

**Comment by MattGal** [comment] 2020-05-18 15:16
Possibly (I'm fighting an issue with them being offline already), but what's the goal here?  Currently for the emulator setup we have, they're booted as services by systemd.

The tricky part we'd have to solve for this is that the location of the executable would not be known so resolution of the path becomes a challenge.

**Comment by EgorBo** [comment] 2020-05-18 15:18
@MattGal 

> but what's the goal here? 

To be consistent with iOS where Xharness does boot them

> solve for this is that the location of the executable

what executable?

**Comment by MattGal** [comment] 2020-05-18 15:20
> what executable?

The emulator.  On linux, it's $ANDROID_SDK_ROOT/emulator/emulator , but this could be anywhere.

**Comment by MattGal** [comment] 2020-05-18 15:52
@EgorBo , after discussing with the other XHarness team members I think this is a non-starter for Android.  When using iOS simulator, one always knows the OS (it's always MacOS) and the simulator is always in a static location relative to XCode.  On Android, we support running from Windows, Linux, and MacOS, there can be any number of emulators and devices attached to the machine, and the location of these emulators can be anywhere.  

XHarness will always print error messages ( I can try to make them extra-explicit) when no usable devices are found, but as I can conceive of no reliable way to find the emulators and start them (and since finding and starting random processes on the user's machine might be unwanted ) I am closing this.  

If you have a reliable strategy for finding and starting emulators that works on all three OSes we can certainly discuss it at a later juncture.

**Comment by mattleibow** [comment] 2023-10-16 15:45
We could use `adb shell getprop sys.boot_completed` (or `dev.bootcomplete`) and see if it is done.

**Comment by ivanpovazan** [comment] 2024-10-03 14:40
Duplicate of https://github.com/dotnet/xharness/issues/393

**Closed by ivanpovazan** 2024-10-03 14:40 UTC
Labels: enhancement, question, android
